name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: Cancel previous runs
      uses: Homebrew/actions/cancel-previous-runs@master
      with:
        workflow: ${{ github.workflow }}
        event: pull_request

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - run: brew test-bot
