name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request:
    
jobs:
  cancel_previous_runs:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
        
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: Set up Homebrew
      id: setup
      uses: Homebrew/actions/setup-homebrew@master
    
    - name: Cache gems
        uses: actions/cache@v2
        with:
          path: ${{steps.setup.outputs.gems-path}}
          key: ${{runner.os}}-rubygems-${{steps.setup.outputs.gems-hash}}
          restore-keys: ${{runner.os}}-rubygems-

    - run: brew test-bot
