name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: Cancel previous runs
      if: matrix.os == 'ubuntu-latest'
      uses: Homebrew/actions/cancel-previous-runs@master
      with:
        workflow: 'main.yml'
        event: pull_request

    - name: Set up Homebrew
      if: succeeded() || failed()
      uses: Homebrew/actions/setup-homebrew@master

    - run: brew test-bot perl
