name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request:
    
jobs:
  cancel_previous_runs:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
        
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master
      
    - name: Linux edgecase
      if: matrix.os == 'ubuntu-latest'
      run: brew reinstall -s perl  # https://github.com/Homebrew/linuxbrew-core/issues/4808

    - run: brew test-bot
